[INCLUDES]
before = common.conf

[Definition]
_daemon = sshd
failregex = ^%(__prefix_line)s(?:error: PAM: )?[aA]uthentication (?:failure|error|failed) for .* from <HOST>( via \S+)?\s*$
            ^%(__prefix_line)sInvalid user .* from <HOST>\s*$
            ^%(__prefix_line)s[iI]nvalid user .* from <HOST> port \d+\s*$
            ^%(__prefix_line)sUser .+ from <HOST> not allowed because not listed in AllowUsers\s*$
            ^%(__prefix_line)sFailed \S+ for .* from <HOST> port \d+\s*$

ignoreregex =
